import type { CRMRecord, SkippedRecord } from '@/types'

/** Shared mock CRM fixtures (expanded by real API path in Step 11). */
export const MOCK_CRM_RECORDS: CRMRecord[] = [
  {
    created_at: '2026-01-15T10:00:00.000Z',
    name: 'John Doe',
    email: 'john.doe@example.com',
    country_code: '+91',
    mobile_without_country_code: '9876543210',
    company: 'GrowEasy',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    lead_owner: 'Agent A',
    crm_status: 'GOOD_LEAD_FOLLOW_UP',
    crm_note: '',
    data_source: 'leads_on_demand',
    possession_time: '',
    description: '',
  },
  {
    created_at: '2026-01-15T10:05:00.000Z',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    country_code: '+91',
    mobile_without_country_code: '9876543211',
    company: 'Tech Solutions',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    lead_owner: 'Agent B',
    crm_status: 'DID_NOT_CONNECT',
    crm_note: '',
    data_source: 'meridian_tower',
    possession_time: '',
    description: '',
  },
  {
    created_at: '2026-01-15T10:10:00.000Z',
    name: 'Rajesh Patel',
    email: 'rajesh.patel@example.com',
    country_code: '+91',
    mobile_without_country_code: '9876543212',
    company: 'Startup Inc',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    lead_owner: 'Agent C',
    crm_status: 'BAD_LEAD',
    crm_note: '',
    data_source: 'eden_park',
    possession_time: '',
    description: '',
  },
  {
    created_at: '2026-01-15T10:15:00.000Z',
    name: 'Priya Singh',
    email: 'priya.singh@example.com',
    country_code: '+91',
    mobile_without_country_code: '9876543213',
    company: 'Enterprise Corp',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    lead_owner: 'Agent D',
    crm_status: 'SALE_DONE',
    crm_note: '',
    data_source: 'sarjapur_plots',
    possession_time: '',
    description: '',
  },
]

export const MOCK_SKIPPED: SkippedRecord[] = [
  {
    row: 5,
    reason: 'No email or mobile number found',
    raw: { Notes: 'Call back later' },
  },
]
